name: datebase
description: History in your pocket.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3 # default
  sembast: ^2.4.3 # database management
  path_provider: ^1.6.7 # to get the path for storing data
  provider: ^4.1.1 # state management
  carousel_slider: ^2.0.0 # to implement Months in datepicker
  dio: ^3.0.9 # for connectivity
  dio_http_cache: ^0.2.6 # to perform http requests

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Muli-Bold
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
